[deploy]
build.command = "echo 'Building...'"

[build]
builder = "nixpacks"

[[services]]
name = "main-bot"
source_path = "."
run = "python main_bot.py"

[[services]]
name = "admin-bot" 
source_path = "."
run = "python admin_bot.py"
